/* oxlint-disable */
import { createContext, useCallback, useContext, useEffect, useMemo, useState } from 'react'
import type { FormEvent, ReactNode } from 'react'
import { BrowserRouter, Link, Navigate, NavLink, Route, Routes, useLocation, useNavigate } from 'react-router-dom'
import { ApiError, api, setAccessToken } from './services/api'
import type { Session, User, UserInput } from './types/api'
import './App.css'

type AuthValue = { authenticated: boolean; restoring: boolean; login: (email: string, password: string) => Promise<void>; logout: () => Promise<void> }
const AuthContext = createContext<AuthValue | null>(null)
const empty: UserInput = { name: '', zip_code: '', street: '', number: '', complement: '', neighborhood: '', city: '', state: '' }
const message = (error: unknown) => error instanceof ApiError ? error.message : 'Não foi possível concluir a solicitação. Tente novamente.'
function useAuth() { const value = useContext(AuthContext); if (!value) throw new Error('AuthProvider is required'); return value }
function Loading() { return <div className="loading"><span className="spinner" aria-label="Carregando" /></div> }
function Notice({ error, success }: { error?: string; success?: string }) { return error || success ? <p className={`notice ${error ? 'error' : 'success'}`} role={error ? 'alert' : 'status'}>{error || success}</p> : null }

function AuthProvider({ children }: { children: ReactNode }) {
  const [authenticated, setAuthenticated] = useState(false); const [restoring, setRestoring] = useState(true)
  useEffect(() => { api.refresh().then(() => setAuthenticated(true)).catch(() => setAccessToken(null)).finally(() => setRestoring(false)) }, [])
  const login = async (email: string, password: string) => { await api.login(email, password); setAuthenticated(true) }
  const logout = async () => { try { await api.logout() } finally { setAccessToken(null); setAuthenticated(false) } }
  const value = useMemo(() => ({ authenticated, restoring, login, logout }), [authenticated, restoring])
  return <AuthContext.Provider value={value}>{children}</AuthContext.Provider>
}
function Protected({ children }: { children: ReactNode }) { const { authenticated, restoring } = useAuth(); const location = useLocation(); return restoring ? <Loading /> : authenticated ? <>{children}</> : <Navigate to="/entrar" replace state={{ from: location }} /> }
function Layout({ children }: { children: ReactNode }) { const { logout } = useAuth(); const navigate = useNavigate(); const [open, setOpen] = useState(false); const leave = async () => { await logout(); navigate('/entrar') }; return <div className="app"><header className="topbar"><Link className="brand" to="/perfil"><span>i</span> Identidade Local</Link><button className="menu" onClick={() => setOpen(!open)} aria-label="Alternar menu" aria-expanded={open}>☰</button><nav className={open ? 'nav open' : 'nav'}><NavLink to="/perfil">Perfil</NavLink><NavLink to="/sessoes">Sessões</NavLink><button onClick={leave}>Sair</button></nav></header><main className="content">{children}</main></div> }
function Heading({ eyebrow, title, description }: { eyebrow: string; title: string; description: string }) { return <header className="heading"><p>{eyebrow}</p><h1>{title}</h1><span>{description}</span></header> }

function AddressFields({ value, onChange, lookup }: { value: UserInput; onChange: (value: UserInput) => void; lookup: (zip: string) => Promise<void> }) {
  const [loading, setLoading] = useState(false); const [hint, setHint] = useState('')
  const set = (field: keyof UserInput, text: string) => onChange({ ...value, [field]: text })
  const search = async () => { const zip = value.zip_code.replace(/\D/g, ''); if (zip.length !== 8) { setHint('Informe os 8 dígitos do CEP para consultar.'); return }; setLoading(true); setHint(''); try { await lookup(zip); setHint('Endereço preenchido. Revise e complete o número, se necessário.') } catch (error) { setHint(message(error)) } finally { setLoading(false) } }
  return <fieldset className="address"><legend>Endereço</legend><div className="grid"><label>CEP <div className="with-button"><input value={value.zip_code} onChange={(e) => set('zip_code', e.target.value.replace(/\D/g, '').slice(0, 8))} onBlur={search} inputMode="numeric" maxLength={8} placeholder="00000000" /><button type="button" className="secondary" onClick={search} disabled={loading}>{loading ? 'Buscando…' : 'Buscar'}</button></div></label><label className="wide">Rua <input value={value.street} onChange={(e) => set('street', e.target.value)} /></label><label>Número <input value={value.number} onChange={(e) => set('number', e.target.value)} /></label><label>Complemento <input value={value.complement} onChange={(e) => set('complement', e.target.value)} /></label><label>Bairro <input value={value.neighborhood} onChange={(e) => set('neighborhood', e.target.value)} /></label><label>Cidade <input value={value.city} onChange={(e) => set('city', e.target.value)} /></label><label>UF <input value={value.state} onChange={(e) => set('state', e.target.value.toUpperCase().slice(0, 2))} maxLength={2} placeholder="SP" /></label></div><small>{hint || 'Não encontrou o CEP? Preencha os campos manualmente.'}</small></fieldset>
}
function AuthShell({ title, text, children }: { title: string; text: string; children: ReactNode }) { return <div className="auth"><section className="intro"><Link className="brand light" to="/entrar"><span>i</span> Identidade Local</Link><div><p>Sua identidade, sob seu controle</p><h1>{title}</h1><span>{text}</span></div><small>Dados protegidos, endereço simplificado e sessões sob controle.</small></section><section className="auth-panel">{children}</section></div> }

function Register() { const navigate = useNavigate(); const [form, setForm] = useState({ ...empty, email: '', password: '', confirmation: '' }); const [error, setError] = useState(''); const [success, setSuccess] = useState(''); const [busy, setBusy] = useState(false); const setAddress = (next: UserInput) => setForm((old) => ({ ...old, ...next })); const lookup = async (zip: string) => setAddress({ ...form, ...await api.lookupAddress(zip) }); const submit = async (e: FormEvent) => { e.preventDefault(); setError(''); if (form.password !== form.confirmation) { setError('As senhas precisam ser iguais.'); return }; setBusy(true); try { await api.register(form); setSuccess('Conta criada com sucesso. Redirecionando…'); window.setTimeout(() => navigate('/entrar'), 800) } catch (err) { setError(message(err)) } finally { setBusy(false) } }; return <AuthShell title="Crie sua identidade" text="Comece com seus dados essenciais. Você poderá atualizar seu perfil quando quiser."><form className="card" onSubmit={submit}><div className="grid"><label className="wide">Nome completo <input required minLength={2} value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} autoComplete="name" /></label><label className="wide">E-mail <input required type="email" value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })} autoComplete="email" /></label><label>Senha <input required type="password" minLength={8} value={form.password} onChange={(e) => setForm({ ...form, password: e.target.value })} autoComplete="new-password" /></label><label>Confirmar senha <input required type="password" minLength={8} value={form.confirmation} onChange={(e) => setForm({ ...form, confirmation: e.target.value })} autoComplete="new-password" /></label></div><AddressFields value={form} onChange={setAddress} lookup={lookup} /><Notice error={error} success={success} /><button className="primary" disabled={busy}>{busy ? 'Criando conta…' : 'Criar conta'}</button><p className="footer">Já tem uma conta? <Link to="/entrar">Entrar</Link></p></form></AuthShell> }
function Login() { const { login, authenticated } = useAuth(); const navigate = useNavigate(); const location = useLocation(); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [error, setError] = useState(''); const [busy, setBusy] = useState(false); const from = (location.state as { from?: { pathname?: string } } | null)?.from?.pathname || '/perfil'; if (authenticated) return <Navigate to="/perfil" replace />; const submit = async (e: FormEvent) => { e.preventDefault(); setBusy(true); setError(''); try { await login(email, password); navigate(from, { replace: true }) } catch (err) { setError(message(err)) } finally { setBusy(false) } }; return <AuthShell title="Boas-vindas de volta" text="Entre para gerenciar seus dados e dispositivos conectados."><form className="card compact" onSubmit={submit}><label>E-mail <input required type="email" value={email} onChange={(e) => setEmail(e.target.value)} autoComplete="email" /></label><label>Senha <input required type="password" value={password} onChange={(e) => setPassword(e.target.value)} autoComplete="current-password" /></label><Notice error={error} /><button className="primary" disabled={busy}>{busy ? 'Entrando…' : 'Entrar'}</button><p className="footer">Ainda não tem conta? <Link to="/cadastro">Criar conta</Link></p></form></AuthShell> }

function Profile() { const [form, setForm] = useState<UserInput>(empty); const [email, setEmail] = useState(''); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [success, setSuccess] = useState(''); const load = useCallback(async () => { try { const user = await api.getProfile(); setEmail(user.email); setForm(toInput(user)) } catch (err) { setError(message(err)) } finally { setLoading(false) } }, []); useEffect(() => { void load() }, [load]); const lookup = async (zip: string) => { const address = await api.lookupAddress(zip); setForm((old) => ({ ...old, ...address })) }; const submit = async (e: FormEvent) => { e.preventDefault(); setBusy(true); setError(''); try { setForm(toInput(await api.updateProfile(form))); setSuccess('Perfil atualizado com sucesso.') } catch (err) { setError(message(err)) } finally { setBusy(false) } }; if (loading) return <Loading />; return <Layout><Heading eyebrow="Minha conta" title="Seu perfil" description="Mantenha seus dados e endereço sempre atualizados." /><form className="card page-card" onSubmit={submit}><div className="grid"><label className="wide">Nome completo <input required minLength={2} value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} /></label><label className="wide">E-mail <input value={email} disabled /><small>O e-mail de acesso não pode ser alterado nesta etapa.</small></label></div><AddressFields value={form} onChange={setForm} lookup={lookup} /><Notice error={error} success={success} /><button className="primary" disabled={busy}>{busy ? 'Salvando…' : 'Salvar alterações'}</button></form></Layout> }
function Sessions() { const [sessions, setSessions] = useState<Session[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [busy, setBusy] = useState(''); const load = useCallback(async () => { try { setSessions(await api.getSessions()) } catch (err) { setError(message(err)) } finally { setLoading(false) } }, []); useEffect(() => { void load() }, [load]); const revoke = async (id: string) => { setBusy(id); try { await api.deleteSession(id); setSessions((old) => old.filter((item) => item.id !== id)) } catch (err) { setError(message(err)) } finally { setBusy('') } }; return <Layout><Heading eyebrow="Segurança" title="Sessões ativas" description="Revogue o acesso de dispositivos que você não reconhece ou não utiliza mais." /><Notice error={error} />{loading ? <Loading /> : <section className="sessions">{sessions.length === 0 ? <div className="empty"><strong>Nenhuma sessão ativa</strong><p>Novas sessões aparecerão aqui quando você entrar em um dispositivo.</p></div> : sessions.map((session) => <article className="session" key={session.id}><b>⌁</b><div><h2>{session.user_agent || 'Dispositivo desconhecido'}</h2><p>Ativa desde {date(session.created_at)} · último uso {date(session.last_used_at)}</p><small>Expira em {date(session.expires_at)}</small></div><button className="danger" onClick={() => revoke(session.id)} disabled={busy === session.id}>{busy === session.id ? 'Revogando…' : 'Revogar'}</button></article>)}</section>}</Layout> }
function toInput(user: User): UserInput { return { name: user.name, zip_code: user.zip_code || '', street: user.street || '', number: user.number || '', complement: user.complement || '', neighborhood: user.neighborhood || '', city: user.city || '', state: user.state || '' } }
function date(value: string) { return new Intl.DateTimeFormat('pt-BR', { dateStyle: 'medium', timeStyle: 'short' }).format(new Date(value)) }
function App() { return <BrowserRouter><AuthProvider><Routes><Route path="/entrar" element={<Login />} /><Route path="/cadastro" element={<Register />} /><Route path="/perfil" element={<Protected><Profile /></Protected>} /><Route path="/sessoes" element={<Protected><Sessions /></Protected>} /><Route path="*" element={<Navigate to="/perfil" replace />} /></Routes></AuthProvider></BrowserRouter> }
export default App
